name: Tests

on: 
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'

jobs:
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        rev: [nightly]

    steps:
      - uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}

      - name: Prepare
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/lazy/plenary.nvim

      - name: Run tests
        run: |
          nvim --version
          make test
  release:
      name: Release
      runs-on: ubuntu-latest
      permissions:
        contents: write
      needs: [unit_tests]
      if: startsWith(github.ref, 'refs/tags/')
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: leafo/gh-actions-lua@v9
        - name: Prepare environment
          run: |
            echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

        - name: Generate release notes
          run: |
            lua scripts/generate_release_notes.lua ${{ env.TAG }} > ${{ github.workspace }}-RELEASE_NOTES.md

        - name: Publish GitHub release
          uses: softprops/action-gh-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            body_path: ${{ github.workspace }}-RELEASE_NOTES.md
            prerelease: ${{ contains(env.TAG, 'rc') }}
